### ISSUE TITLE
PHP Fatal error:  Can't use function return value in write context

### ISSUE THREAD

**Issue by yzenezy** [ltb-project/ldap-scripts#26] opened 2021-07-19 01:42 UTC
Hi,

I've got Self Service Password running on CentOS 7. It was installed via yum/rpm quite a while ago. It's been updated recently and is currently on version: self-service-password-1.4.3-1.el7.noarch.

It's been working great until recently and now I get the following error in the apache logs:

`PHP Fatal error:  Can't use function return value in write context in /usr/share/self-service-password/lib/vendor/phpmailer/phpmailer/src/PHPMailer.php on line 1687
`

Can someone please assist in solving the above issue? Please let me know what other information I can provide if needed.

Kind regards,
Tom

**Comment by yzenezy** [comment] 2021-07-19 04:35
I've merged the original config file with the new config file and upgraded to php74 which seems to have fixed the issues. Sorry for the noise.

**Comment by faust64** [comment] 2021-07-19 11:44
PHP4?! In EL7, you should at least be able to run with PHP5. While non-default repos could help you upgrade to PHP7.x.

Anyway, good to know you fixed it. Closing that case.
If you have any further issue with SelfServicePassword, feel free to report them over here: https://github.com/ltb-project/self-service-password

**Closed as completed by faust64** 2021-07-19 11:44 UTC
Labels: question

**Comment by yzenezy** [comment] 2021-07-19 21:53
Sorry, that was a typo! I upgraded to PHP 7.4.21 Obviously typing too fast and not checking properly. My CentOS7 install had PHP 5.4.16 which was part of the problem. I've edited my comment above to indicate the correct version to which I upgraded.

**Comment by coudot** [comment] 2021-07-20 08:10
Note that this issue was opened in the incorrect projet. To report issue for Self Service Password: https://github.com/ltb-project/self-service-password/issues

**Comment by yzenezy** [comment] 2021-07-20 22:08
Sorry, yes. Can I move this to the other project thread? Or shall I post a reference from there to here?

**Comment by coudot** [comment] 2021-07-21 08:16
No it's ok we can leave it here, as it is not a bug we have to fix in the code.
